### ISSUE TITLE
Project Completion Checklist

### ISSUE THREAD

**Issue by gak5275** [gak5275/StardewDIGIT210#14]
# Website contents
### An index.html "home" page:
- [x] Introduce your project's research questions
- [x] Share your "big picture" conclusions (often this is written last!).
- [x] Indicate what we can find in the site. Share a data visualization on the main page if it helps to illuminate an interesting finding.
- [x] Provide a [Creative Commons licenseLinks to an external site.](https://creativecommons.org/share-your-work/) of the team's choice, as well as acknowledgement of the grounds/permissions for sharing your source text collections

### A page about your text corpus:
- [x] Indicate the source of your text corpus (collection of source documents) by name and link to it.
- [x] Describe anything remarkable about that resource: why was this a good basis for your project? 
- [x] Discuss how you prepared/altered the texts for your corpus analysis.  
Reading views of texts are optional for this course, but may be desirable depending on your project if helpful to illustrate something in your data or preserve an unusual resource. 

### A Methods page
- [x] Prepare a methods page to explain and illustrate the methods your team applied in this project.
- [x] Discuss how you prepared the texts for analysis and what in what formats you're working with the texts: (plain text, spreadsheets as TSV files, regex-to-XML, schemas). 
- [x] Feature some of your code (regex, Python, XQuery, etc): You can set code blocks in HTML that store indentation using the pre element, and you can represent angle brackets directly by using their escape characters: &lt; for < and &gt; for >. 
- [x] Include link to the "code view" of your GitHub repo (can be in the footer or nav bar).

### Page(s) sharing data analysis with tables, visualizations, and discussion
Analysis pages should include:
- [x] Required: Some Python-based application of natural language processing (NLP, part-of-speech analysis, topic modeling, etc.) 
- [x] Required: XQuery-based output.
Optional: visualizations from Antconc and Voyant.
- [x] Visualizations should include at least two of the following:
network visualization(s) (interactive or static)
topic modeling visualization(s)
SVG graphs
HTML tables showing detailed information (sorted counts, data that isn't easily visualized in a summary graph).
- [x] Visualizations and charts must be accompanied by descriptive captions and paragraphs of discussion, at least one paragraph for each visualization. 

### A feature of problems faced in the analysis:
- [x] Discuss: problematic data / issues in the autotagging, anything open to misinterpretation, questions not fully answered.
- [x] Discuss the limits of your analysis and conclusions to put your findings into appropriate context.
This reflection should be a central feature, but may appear anywhere that makes sense in your site (index page, methods page, analysis page, etc.)

### Credits (About the team) page
This page credits the project team members and the context for the project. 
- [x] Indicate when/where/why you developed this project. 
- [x] Introduce the team members
- [x] Sum up what areas each team member worked on.
Ideally this is directed to people outside our class. (Don't just say it was developed for your DIGIT 210 class, but identify as Large-Scale Text Analysis class at Penn State Behrend...)
