### ISSUE TITLE
Stardew Milestone 3

### ISSUE THREAD

**Issue by gak5275** [gak5275/StardewDIGIT210#3]
- [x] A cleaned and curated collection of text files (.txt file extensions). You can work on these with Python NLP now if they're ready. There should be 34 of these in total, each containing all of a single character's dialogue.

- [x] A curated version of those files in carefully structured XML (.xml file extensions) ready to be loaded into our eXist-dB XML database for XQuery work. 

Note: XQuery work will also be generating curated subsets of text files and csv / tsv files as we experiment with NLP, network analysis, and rolling your own SVG visualizations from your queries. The structures of your XML files should make a database that you'll be querying--that's why those container structures you create are important: chapter, book, speech, stage as wrappers around distinct kinds of info.

- [x] To curate that XML carefully, prepare a Relax NG schema for the project XML. Be attentive to data types—where do you need dates, integers, timestamps (talk to me about these: Official ISO-formatted timestamps they will need a little regex-reformatting and I can help)? And where do you want a set list of values for attributes?

Store all these things mindfully in your GitHub repo and make sure everyone on the team is keeping their repositories up to date.

- [x] Start up the Python! Experiment with some Python NLP (play with word embeddings data, topic modeling, tinker and experiment with methods you're reading about): try  outputting some preliminary findings of interest to discuss with your team. As you're learning things, write up some nice markdown documentation for the team (and future DIGIT students will thank you!) Share links and resources and guidance for each other.

- [x] Work on your website: Make a "splash" page that invites people to learn more about what you're doing: Develop some content even just on the index.html page that describes your project so far forecasts topics and research questions of interest.  Do some serious HTML + CSS here, and make sure your team likes it.
