### ISSUE TITLE
Stardew Milestone 4

### ISSUE THREAD

**Issue by gak5275** [gak5275/StardewDIGIT210#8]
- [x] Prepare an XML corpus for your project. (The team can continue to update the XML files as you add markup, but by this milestone, the basic structure of your XML files should be set so you can be writing XQuery on your files.)
- [x] Schema check stage: Prepare a single project Relax NG schema to associate it with your files. Ask Dr. B for help to review your project schema.
- [x] Correct any errors if your code isn't well-formed or valid against the project schema.
- [x] Project markdown: Team members have drafted a record of project meetings/tasks/documentation that are part of the GitHub repo, in GitHub Issues posts or in markdown files.
- [x] Website/GitHub Readme development: Work on drafting your research questions and what things you will be trying out on your corpus: share these on the website and Readme. Things to try/think about/ review:
Python natural language processing: topic modeling, word vector search, named entity recognition, etc.
XQuery can pull chunks of your collection (like all the stage directions, or all the spoken content) into separate text files for corpus work.
XQuery or Python can also prepare networks of data: (example: which characters show up/are mentioned together in the same episodes)
- [x] Discuss/customize research questions/directions with the team and Dr. B
- [x] Team members experiment with writing XQuery over all of some of the team XML is present in the team GitHub repo, and some results of that XQuery are shared, if not on the website, at least in the repo. (Save queries in the project-query folder)
